# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 1

before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/kube-apiserver-audit-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - -X main.Version={{.Version}}
    goarch:
      - amd64
      - arm64

archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- tolower (title .Os) }}-
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

dockers:
  - image_templates:
      - ghcr.io/{{ .Env.REPO_OWNER_LOWER }}/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/amd64
  - image_templates:
      - ghcr.io/{{ .Env.REPO_OWNER_LOWER }}/{{ .ProjectName }}:{{ .Version }}-arm64
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/arm64
docker_manifests:
- name_template: ghcr.io/{{ .Env.REPO_OWNER_LOWER }}/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/{{ .Env.REPO_OWNER_LOWER }}/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/{{ .Env.REPO_OWNER_LOWER }}/{{ .ProjectName }}:{{ .Version }}-arm64
- name_template: ghcr.io/{{ .Env.REPO_OWNER_LOWER }}/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/{{ .Env.REPO_OWNER_LOWER }}/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/{{ .Env.REPO_OWNER_LOWER }}/{{ .ProjectName }}:{{ .Version }}-arm64
