{
 "title": "Kube-apiserver Audit Exporter Metrics (Resource Namespace Filtered)",
 "tags": [
  "kubernetes",
  "apiserver",
  "audit-exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "resourceNamespace",
    "label": "Resource Namespace",
    "query": "label_values(apiserver_requests, resourceNamespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 Requests by User Agent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (userAgent) (rate(apiserver_requests{container=\"exporter\", job=\"kube-apiserver-audit-exporter\", namespace=\"monitoring\", resourceNamespace=~\"$resourceNamespace\"}[5m])))",
     "legendFormat": "{{userAgent}}"
    }
   ]
  },
  {
   "title": "Requests by Response Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (responseCode) (rate(apiserver_requests{container=\"exporter\", job=\"kube-apiserver-audit-exporter\", namespace=\"monitoring\", resourceNamespace=~\"$resourceNamespace\"}[5m]))",
     "legendFormat": "Code {{responseCode}}"
    }
   ]
  },
  {
   "title": "Top 10 resourceNamespaces (by Resources Requested)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by (resourceNamespace) (rate(apiserver_requests{container=\"exporter\", job=\"kube-apiserver-audit-exporter\", namespace=\"monitoring\", resourceNamespace=~\"$resourceNamespace\"}[5m])))",
     "legendFormat": "{{resourceNamespace}}"
    }
   ]
  },
  {
   "title": "Top 10 Resources Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, sum by (resource) (rate(apiserver_requests{container=\"exporter\", job=\"kube-apiserver-audit-exporter\", namespace=\"monitoring\", resourceNamespace=~\"$resourceNamespace\"}[5m])))",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}